# Generated by Django 4.0.6 on 2022-08-22 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addres', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
                ('occupied', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Request_donate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('state', models.BooleanField(choices=[(0, 'Available'), (1, 'Booked')], default=0)),
                ('office', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='donations.office')),
            ],
        ),
    ]
