# Generated by Django 4.0.6 on 2022-08-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_donate',
            name='state',
            field=models.BooleanField(choices=[(0, 'Free'), (1, 'Booked')], default=0),
        ),
    ]
