# Generated by Django 4.0.6 on 2022-08-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_request_donate_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_donate',
            name='office_id',
            field=models.IntegerField(default='exit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request_donate',
            name='state',
            field=models.BooleanField(choices=[(0, 'Available'), (1, 'Booked')], default=0),
        ),
    ]
