# Generated by Django 4.0.6 on 2022-08-16 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_request_donate_office_id_alter_request_donate_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addres', models.CharField(max_length=50)),
                ('capacity', models.IntegerField()),
                ('occupied', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='request_donate',
            name='office_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='donations.office_list'),
        ),
    ]
