# Generated by Django 4.0.6 on 2022-08-16 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_office_list_alter_request_donate_office_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Office_list',
            new_name='Office',
        ),
        migrations.RenameField(
            model_name='request_donate',
            old_name='office_id',
            new_name='office',
        ),
    ]
